# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oginsta', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
